### ISSUE TITLE
Add Payouts Service to list of Projects

### ISSUE THREAD

**Issue by pippinsplugins** [sandhillsdevelopment/site#68]
The Payouts Service needs to be added to the projects section of the home page.

Here's a blurb for it:

>Managed payout disbursement for affiliate and vendor commissions

Related https://github.com/sandhillsdevelopment/site/issues/67

**Comment by SeanChDavis** [comment]
Adjusted the title here because Projects show on the front page and on the Projects page. [Each project](https://sandhillsdev.com/wp-admin/post.php?post=882&action=edit) has one single data source that builds out its front page section as well as its Projects page section. So I'd also need content for the Projects page.

<img width="1025" alt="Screenshot 2021-05-05 112447" src="https://user-images.githubusercontent.com/2359131/117175532-93b7e680-ad94-11eb-94d8-06376c517758.png">

**Comment by pippinsplugins** [comment]
@SDavisMedia oh right, forgot about that!

I'll get a full version written up soon.

**Comment by SeanChDavis** [comment]
@pippinsplugins Awesome. I took the liberty of creating the entry on the site with what I think is the necessary information. All it's missing is the aforementioned post_content. https://sandhillsdev.com/wp-admin/post.php?post=1075&action=edit (if it claims I'm in there, you can takeover)

Feel free to type it in place and publish!

**Comment by SeanChDavis** [comment]
Also, if you want to add a new Project type instead of "eCommerce Service" which was used for Sellbird, just let me know what you want, or you can add it [here](https://sandhillsdev.com/wp-admin/post.php?post=873&action=edit). You'd edit the **Project type** field and add a new line to the **Choices** textarea. Update that and then refresh the edit screen for the new Project. Then you can select it and everything should work/output as expected.

**Comment by pippinsplugins** [comment]
@SDavisMedia take a look! https://sandhillsdev.com/projects/

**Comment by SeanChDavis** [comment]
@pippinsplugins Excellent! Let me know what order you want it to show up in the list and I'll set that.

**Comment by pippinsplugins** [comment]
Let's keep it first in the list for now.
